# Generated by Django 5.2.7 on 2025-11-11 04:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (Kode Barang)', max_length=50, null=True, unique=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('asset_account', models.ForeignKey(limit_choices_to={'type': 'ASET'}, on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('hpp_account', models.ForeignKey(limit_choices_to={'type__in': ['BEBAN', 'BEBAN_LAIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='hpp_items', to='accounting.account')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('BELI', 'Pembelian Stok'), ('JUAL', 'Penjualan (HPP)'), ('PENYESUAIAN', 'Penyesuaian Stok (Rusak/Hilang)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='accounting.inventoryitem')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
            ],
        ),
    ]
