# Generated by Django 5.2.7 on 2025-11-13 16:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_contact_journalentry_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('useful_life_months', models.IntegerField(default=60)),
                ('is_fully_depreciated', models.BooleanField(default=False)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('accumulated_depreciation_account', models.ForeignKey(limit_choices_to={'normal_balance': 'KREDIT', 'type': 'ASET'}, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_akum', to='accounting.account')),
                ('asset_account', models.ForeignKey(limit_choices_to={'normal_balance': 'DEBIT', 'type': 'ASET'}, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account')),
                ('depreciation_expense_account', models.ForeignKey(limit_choices_to={'type__in': ['BEBAN', 'BEBAN_OPERASIONAL', 'BEBAN_LAIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_beban', to='accounting.account')),
            ],
        ),
    ]
