# Generated by Django 5.2.7 on 2025-11-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_fixedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='transaction_type',
            field=models.CharField(choices=[('BELI', 'Pembelian Stok'), ('JUAL', 'Penjualan (HPP)'), ('PENYESUAIAN', 'Penyesuaian Stok (Rusak/Hilang)'), ('RETUR_JUAL', 'Retur Penjualan')], max_length=20),
        ),
    ]
