# Generated by Django 5.2.7 on 2025-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_inventorylog_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ASET', 'Aset'), ('LIABILITAS', 'Liabilitas'), ('EKUITAS', 'Ekuitas'), ('PENDAPATAN', 'Pendapatan'), ('BEBAN', 'Beban (HPP)'), ('BEBAN_OPERASIONAL', 'Beban Operasional'), ('BEBAN_LAIN', 'Beban Lainnya')], max_length=20),
        ),
    ]
