# Generated by Django 5.2.7 on 2025-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
